---
abstract: 'SMS::Send backend for the Nexmo.com SMS service.'
author:
  - 'Michiel Beijen <michiel.beijen@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112150'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SMS-Send-Nexmo
requires:
  Nexmo::SMS: 0
  SMS::Send: 0
resources:
  bugtracker: https://github.com/mwb/SMS-Send-Nexmo/issues
  repository: git://github.com/mwb/SMS-Send-Nexmo.git
version: 0.12
